### PR TITLE
Bugfix larsg 328 original quote cut off, not wrapping

### PR DESCRIPTION
**Pull request by larsgson**
Editable original quote in TSV content card is cut off, not wrapping

## Test Instructions

- [ ] Confirm editable and autosize in Gateway edit with long original quote, for instance in John 3:4 (in Translation Notes)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@larsgson Seeing an issue that boxes are around tNotes fields even when unselected.  Old program showed:

Screen Shot 2022-08-22 at 8 43 47 AM

New program shows:

Screen Shot 2022-08-22 at 8 44 53 AM

Can you remove the boxes when not selected?

**Comment by larsgson** [comment]
I have now changed TextAreaAutosize to be without border when not in focus

**Comment by PhotoNomad0** [comment]
> I have now changed TextAreaAutosize to be without border when not in focus

@larsgson It doesn't look like you have pushed up your fix yet?

**Review by PhotoNomad0 — APPROVED** [review]
LGTM

**Pull request merged**
